server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由ID，没有固定的规则但要求唯一，建议配合服务名
          uri: http://localhost:8001  #匹配提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言，路径相匹配的进行路由

        - id: payment_routh2 #路由ID，没有固定的规则但要求唯一，建议配合服务名
            uri: http://localhost:8001  #匹配提供服务的路由地址
            predicates:
              - Path=/payment/lb/**   #断言，路径相匹配的进行路由


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

