#服务端口
server:
  port: 7001

#eureka注册中心
eureka:
  instance:
    hostname: eureka7001.com #localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false  #表示不向注册中心注册自己
    fetch-register: false #表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # http://eureka7002.com:7002/eureka